apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aws-ecr-credentials.secret" . }}
  namespace: {{ include "aws-ecr-credentials.namespace" . }}
  labels:
    {{- include "aws-ecr-credentials.labels" . | nindent 4 }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey | b64enc }}
