apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-ecr-credentials.serviceAccount" . }}
  namespace: {{ include "aws-ecr-credentials.namespace" . }}
  labels:
    {{- include "aws-ecr-credentials.labels" . | nindent 4 }}
